version: '3'
services:
  sinyi_web:
    build:
      context: ./
      dockerfile: Dockerfile4WEB
    depends_on:
      - sinyi_api
    image: sinyi_web:latest
    container_name: sinyi_web_instance
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
  sinyi_api:
    build:
      context: ./
      dockerfile: Dockerfile4API
    image: sinyi_api:latest
    container_name: sinyi_api_instance
    expose:
      - "5000"
    volumes:
      - ../../XinYiRecognition:/usr/local/XinYiRecognition
      - ..:/usr/local/xyapi_ws
      - /media/data:/media/data
      - /var/log/sinyi:/var/log/sinyi
      - ./xyapi.conf:/etc/supervisor/conf.d/xyapi.conf
      - ./chi_xy_hanzi.traineddata:/usr/share/tesseract-ocr/4.00/tessdata/chi_xy_hanzi.traineddata
      - ./chi_xy_digits.traineddata:/usr/share/tesseract-ocr/4.00/tessdata/chi_xy_digits.traineddata
      