version: '3'
services:
  web:
    build: 
      context: ./
      dockerfile: Dockerfile4WEB
      args:
        buildno: 1
    ports:
      - "80:80"
  api:
    build:
      context: ./
      dockerfile: Dockerfile4WEB
      args:
        buildno: 2
    ports:
      - "5000:5000"
    volumes:
      - ..:/code
    