version: '3'
services:
  web:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_default:/etc/nginx/conf.d/default
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        buildno: 1
    ports:
      - "5000:5000"
    volumes:
      - ..:/usr/local/xyapi_ws
      - /media/data:/media/data
      - ./xyapi.conf:/etc/supervisor/conf.d/xyapi.conf
      - ../log:/var/log/sinyi
    