version: '3'
services:
  sinyi_web:
    build:
      context: ./
      dockerfile: Dockerfile4WEB
    depends_on:
      - sinyi_api
    restart: always
    image: sinyi_web:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx_default:/etc/nginx/conf.d/default
  sinyi_api:
    build:
      context: ./
      dockerfile: Dockerfile4API
    restart: always
    image: sinyi_api:latest
    ports:
      - "5000:5000"
    volumes:
      - ..:/usr/local/xyapi_ws
      - /media/data:/media/data
      - ./xyapi.conf:/etc/supervisor/conf.d/xyapi.conf
    